### ISSUE TITLE
Program does not check the input file

### ISSUE THREAD

**Issue by richelbilderbeek** [attilaszia/nonogram#1]
When I compile the code with `make`, everything works like a breeze.

When I run the code with `./solver table.cc` my system crashes. I expect that the input is not checked. It would be helpful if it would be checked.

**Comment by attilaszia** [comment]
I don't have time to fix this now, but if you're already looking at the code, feel free to create a patch :)

**Comment by richelbilderbeek** [comment]
Great! If will happily do so :-)

**Comment by richelbilderbeek** [comment]
Produced this Issue on Travis, now handled correctly:

```
$ if [ `./nonogram table.cc` -eq 0 ]; then echo "File not detected as incorrect"; return 1; else echo "File correctly identified as incorrect"; fi
terminate called after throwing an instance of 'std::invalid_argument'
  what():  File has an invalid format
/home/travis/.travis/job_stages: line 53: [: too many arguments
File correctly identified as incorrect
```

**Comment by richelbilderbeek** [comment]
Looks like a little flaw in my `.travis.yml` `if`-statement. But it's fine enough...

**Comment by richelbilderbeek** [comment]
Fixed it!
